import os
from pathlib import Path

def generate_all():
    data_dir = Path("data")
    data_dir.mkdir(exist_ok=True)
    
    # 1. Password Reset Guide (We will write content to compile as PDF later)
    password_reset_title = "User Password Reset & Lockout Recovery Guide"
    password_reset_paras = [
        "This guide describes the standard procedure for resetting user passwords, managing account lockouts, "
        "and recovering credentials on the platform.",
        "1. Standard Password Reset via Portal:",
        "Users can initiate a password reset by navigating to the login screen and clicking 'Forgot Password'. "
        "The system will prompt for the registered email address. If the email matches an active account, "
        "a secure reset link containing a cryptographic token is dispatched. The token remains valid for exactly "
        "30 minutes. Once clicked, the link redirects the user to a page requiring a new password matching our security policy.",
        "2. Password Complexity Requirements:",
        "Passwords must be at least 12 characters in length, containing at least one uppercase letter, one lowercase "
        "letter, one numeric digit, and one special character (e.g., !, @, #, $, %, ^). Repeating characters are "
        "limited to 2 consecutive occurrences.",
        "3. Account Lockout Prevention & Recovery:",
        "To protect against brute-force attacks, accounts are automatically locked after 5 consecutive failed login "
        "attempts. The lockout duration is set to 30 minutes. Users can bypass the lockout wait time by executing "
        "a lockout recovery verification. A recovery email is sent to the address on file containing a 6-digit verification code. "
        "Entering this code allows the user to immediately unlock their account and attempt login or reset their password.",
        "For manual administrator overrides, support agents can navigate to Admin Console > Users, find the locked profile, "
        "and click 'Unlock User Profile'. This takes effect immediately."
    ]
    
    # 2. Account Recovery (TXT)
    account_recovery_content = """Account Recovery Procedures
Document Code: KB-REC-201
Version: 1.4

This document outlines the security procedures for recovering access to a user account when the primary email or credential set is lost.

1. Identity Verification Requirements:
To recover an account, the user must provide proof of identity. Acceptable proofs include:
- The last 4 digits of the payment method on file.
- The original signup date and registration location.
- An authorized domain administrator confirmation.

2. Lost Email Recovery Path:
If a user no longer has access to their registered email address, they must submit a secondary email update request. This requires validation from a billing administrator or a notarized identity statement. The support team will process these requests within 2 business days.

3. Session Revocation:
Upon successful account recovery, all active browser sessions, OAuth authorizations, and API keys are automatically revoked to prevent unauthorized concurrent access.
"""
    
    # 3. MFA Setup (MD)
    mfa_setup_content = """# Multi-Factor Authentication (MFA) Configuration Guide

Multi-Factor Authentication adds a layer of security to user logins.

## Supported MFA Methods
- **Authenticator Apps (TOTP)**: Google Authenticator, Authy, Microsoft Authenticator.
- **SMS Passcodes**: Fallback method for verified mobile numbers.
- **Security Keys**: WebAuthn / FIDO2 security devices.

## Step-by-Step Setup
1. Log in to the User Dashboard and navigate to **Security Settings**.
2. Click **Enable Multi-Factor Authentication**.
3. Select **Authenticator App** (Recommended). The system will generate a QR code and a secret setup key.
4. Scan the QR code with your authenticator app.
5. Enter the 6-digit verification code generated by the app to confirm successful pairing.
6. Save the **MFA Backup Codes** in a secure offline location.

## MFA Recovery
If you lose access to your authenticator device:
- Use one of your 10 single-use Backup Codes. Each backup code is invalid after one use.
- If backup codes are lost, contact your organization's Administrator to reset your MFA configuration. Administrators can reset MFA via `Admin Panel > Users > MFA > Reset MFA`.
"""

    # 4. OAuth Guide (TXT)
    oauth_guide_content = """OAuth 2.0 Configuration and Integration
Document Reference: KB-OAUTH-402

This document explains how to set up OAuth 2.0 clients and scopes for application authorization.

1. Generating Client Credentials:
Navigate to Developer Console > OAuth Clients. Click 'Create Client'.
The system will generate:
- Client ID: A public identifier for your application.
- Client Secret: A private key that must never be shared or exposed in client-side code.

2. Supported OAuth Scopes:
- read:users - Access user profiles.
- write:users - Modify user details.
- read:data - Read customer databases.
- write:data - Write/edit customer database records.

3. Authorization Code Flow:
Applications must redirect users to:
https://api.platform.com/oauth/authorize?response_type=code&client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&scope=read:users

Exchange the returned authorization code for an Access Token by POSTing to /oauth/token.
"""

    # 5. API Authentication (MD)
    api_auth_content = """# API Authentication Guide

All requests to the platform API must be authenticated using API keys or Access Tokens.

## API Key Authentication
API keys are long-lived credentials suitable for server-to-server integrations.

### Generating API Keys
1. Go to the Developer Dashboard.
2. Select **API Credentials**.
3. Click **Generate New API Key**.
4. Copy the key immediately. It will not be shown again for security reasons.

### Usage in Headers
All HTTP requests must include the API key in the custom header `X-API-KEY`.
Example request:
```http
GET /v1/customers HTTP/1.1
Host: api.platform.com
X-API-KEY: plat_key_9823hf98a23gf
Accept: application/json
```
Do not send API keys in URL query parameters, as they are logged by web servers.
"""

    # 6. Bearer Tokens (MD)
    bearer_tokens_content = """# Bearer Token Authentication

Bearer tokens are short-lived JWTs (JSON Web Tokens) used for authorized user sessions.

## Header Format
Bearer tokens must be passed in the `Authorization` header of every API request.
The format is:
`Authorization: Bearer <token>`

Example request headers:
```http
GET /v1/user/profile HTTP/1.1
Host: api.platform.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
Content-Type: application/json
```

## Token Lifespan & Expiration
- Access Tokens: Valid for exactly 1 hour (3600 seconds).
- Refresh Tokens: Valid for 14 days. Used to obtain new access tokens without prompting credentials.
- Expired Token Response: Requests with expired bearer tokens will fail with a `401 Unauthorized` status and error payload `{"error": "token_expired"}`.
"""

    # 7. API Rate Limits (TXT)
    api_rate_limits_content = """API Rate Limits and Throttling
Document Code: KB-API-LIMITS

To ensure service availability, all API keys are subject to rate limiting and request throttling.

1. Default Rate Tiers:
- Developer Sandbox: 60 requests per minute.
- Professional Tier: 1000 requests per minute.
- Enterprise Tier: 5000 requests per minute.

2. Rate Limit Headers:
Every API response contains metadata headers indicating current usage:
- X-RateLimit-Limit: The maximum requests allowed in the window.
- X-RateLimit-Remaining: The number of remaining requests allowed in the current window.
- X-RateLimit-Reset: The Unix epoch time indicating when the current rate limit window resets.

3. Exceeding Limits (HTTP 429):
If rate limits are exceeded, the server returns an HTTP 429 Too Many Requests status code.
The response payload is:
{"error": "rate_limit_exceeded", "message": "Too many requests. Please try again after reset time."}
Integrations must implement exponential backoff and read the X-RateLimit-Reset header.
"""

    # 8. Webhooks (MD)
    webhooks_content = """# Webhook Subscriptions and Delivery

Webhooks allow integrations to receive real-time HTTP POST notifications when events occur.

## Configurable Webhook Events
- `user.created`: Fired when a new user registers.
- `payment.succeeded`: Fired when an invoice is successfully processed.
- `payment.failed`: Fired when a charge attempt fails.

## Webhook Signatures & Security
To verify that webhooks are sent by our platform, we include a signature in the header:
`X-Platform-Signature: t=162387126,v1=98af21d0a87c12f23`

You should verify this signature using your secret webhook key:
```python
import hmac
import hashlib

# Concatenate timestamp and raw body payload
payload = f"t={timestamp}.{raw_body}".encode('utf-8')
expected = hmac.new(webhook_secret.encode('utf-8'), payload, hashlib.sha256).hexdigest()
```
"""

    # 9. Database Integration (MD)
    db_integration_content = """# Database Integration Guidelines

This document outlines configurations for integrating database adapters and connection pool sizes.

## Connection Strings & Settings
For production database integrations, use a structured connection URI:
`postgresql://db_user:password@db_host:5432/platform_prod`

## Connection Pool Configurations
To optimize performance and avoid database connection exhaustion:
- **Default Pool Size**: Set the maximum pool size to 20 connections per server instance.
- **Timeout**: Set the connection timeout to 30 seconds.
- **Idle Connections**: Maintain a minimum of 5 idle connections.

Example database connection setup in configuration:
```python
db_config = {
    "pool_size": 20,
    "max_overflow": 10,
    "pool_timeout": 30,
    "pool_recycle": 1800
}
```
If connection pool limit is exceeded, database connections fail with `InternalServerError` or connection timeout errors.
"""

    # 10. Billing Disputes (TXT)
    billing_disputes_content = """Billing Disputes Policy
Document: KB-BILL-DISPUTE
Status: Published

This document outlines the policy and timelines for customer billing disputes and invoice reviews.

1. Disputing an Invoice:
Customers must notify billing support of any invoice errors or disputes within 30 days of the invoice date. Disputes filed after 30 days are not eligible for retroactive adjustments.

2. Review Procedure & Timeline:
- The Billing Team initiates an investigation within 24 hours of ticket receipt.
- A resolution, adjustment, or formal decision will be delivered to the client within 5 to 7 business days.
- During active disputes, the user's platform access will NOT be suspended, provided the undisputed portion of the bill is paid.

3. Submission:
To open a billing dispute, contact billing@platform.com with the invoice number, disputed amount, and justification.
"""

    # 11. Refund Policy (TXT)
    refund_policy_content = """Platform Refund Policy
Document Code: KB-BILL-REFUND

This policy explains refund eligibility criteria and standard processing timelines.

1. Eligibility:
- Subscription plans are billed in advance and are non-refundable except in cases of service outages exceeding our SLA agreement (99.9% uptime).
- Credit balances are eligible for refund upon request if the account is closed in good standing.

2. Refund Processing Time:
Once a refund is approved by the Billing Administrator, the funds are credited back to the original payment method:
- Credit Card Refunds: Take 5 to 10 business days to appear on the bank statement.
- Bank Transfer/ACH: Take 7 to 14 business days to clear.

3. Chargebacks:
If a customer initiates a chargeback or payment dispute with their bank, the associated platform account is immediately suspended pending verification.
"""

    # 12. Duplicate Charges (MD)
    duplicate_charges_content = """# Resolving Duplicate Billing Charges

Occasionally, processing errors can cause duplicate pending authorizations or dual charges.

## What Causes Duplicate Charges?
- Double-clicking the "Submit Payment" button during checkout.
- Browser page refresh during payment authorization.
- System retries during API network timeouts.

## How to Resolve Duplicate Charges
1. Verify if the duplicate charge is a **Pending Authorization** or a **Posted Transaction**. Pending authorizations usually clear automatically within 3 to 5 business days without debiting funds.
2. If both charges are posted (settled) transactions:
   - Contact support at billing@platform.com.
   - Provide the invoice numbers or transaction IDs.
3. The Billing team will immediately reverse the duplicate payment. The reversed transaction will appear back on your card statement within 5 to 10 business days.
"""

    # 13. Payment Failures (TXT)
    payment_failures_content = """Payment Failures and Declined Cards
Reference: KB-BILL-DECLINE

If a payment attempt fails, the platform sends an email notice and flags the invoice.

1. Common Decline Error Codes:
- Insufficient Funds: The account has insufficient cash. Request the user to top up or use an alternate card.
- Expired Card: The card's expiration date has passed. User must update card details.
- Restrictive Lock: Bank blocked the transaction due to fraud detection. User must call their card issuer to clear the transaction.

2. Retries:
The billing system automatically retries failed invoice charges three times:
- Retry 1: 3 days after initial failure.
- Retry 2: 7 days after initial failure.
- Retry 3: 10 days after initial failure.
If all retries fail, the subscription is automatically downgraded, and platform access is restricted.
"""

    # 14. Browser Cache Issues (MD)
    browser_cache_content = """# Resolving Web App Loading and Display Issues

If parts of the user dashboard or login buttons do not load, it is often due to outdated static files cached in the browser.

## Recommended Fixes
1. **Force Refresh (Hard Reload)**:
   - Windows: Press `Ctrl + F5` or `Ctrl + Shift + R`.
   - Mac: Press `Cmd + Shift + R`.
2. **Clear Application Cache**:
   - Open browser Developer Tools (`F12`).
   - Go to **Application** tab (Chrome) or **Storage** tab (Firefox).
   - Click **Clear Site Data** or **Clear Storage**.
3. **Use Incognito/Private Mode**:
   - Test if the login/loading issue persists in an incognito window. If it works there, clearing cookies and cache will resolve the primary browser issue.
"""

    # 15. Cookie Clearing (TXT)
    cookie_clearing_content = """Troubleshooting Authentication Loops and Cookies
Document: KB-COOKIE-CLEAR

If you are stuck in a continuous redirect loop or login screen refresh, stale authorization cookies must be cleared.

1. Chrome Instructions:
- Click the pad lock icon in the URL address bar.
- Select 'Site Settings' or 'Cookies and site data'.
- Click 'Manage cookies and site data'.
- Click the trash icon next to platform.com to remove the session cookies.
- Refresh the browser and log in again.

2. Firefox Instructions:
- Click the shield icon in the address bar.
- Click 'Clear cookies and site data' button.
- Confirm deletion, reload page, and re-login.

Clearing cookies resolves 95% of redirect loop errors.
"""

    # 16. User Permissions (MD)
    user_permissions_content = """# Role-Based Access Control (RBAC) and Permissions

The platform uses a role-based model to manage user permissions.

## Platform Roles
1. **Owner**: Full administrative control, including billing setup, account deletion, and user role modification.
2. **Administrator**: Can add/remove users, configure APIs, adjust integration settings, but cannot delete the workspace owner.
3. **Editor**: Can read and write database integrations, webhooks, and setup pipelines. Cannot modify users.
4. **Viewer**: Read-only access to dashboard data and analytics.

## Modifying Permissions
To upgrade a user's permission level:
1. Navigate to **Admin Panel > Team Members**.
2. Locate the user and click **Edit Permissions**.
3. Select the new Role from the dropdown list.
4. Click **Save Changes**. The permissions update takes effect on the user's next API request or page load.
"""

    # Write Text and Markdown files
    files = {
        "account_recovery.txt": account_recovery_content,
        "mfa_setup.md": mfa_setup_content,
        "oauth_guide.txt": oauth_guide_content,
        "api_authentication.md": api_auth_content,
        "bearer_tokens.md": bearer_tokens_content,
        "api_rate_limits.txt": api_rate_limits_content,
        "webhooks.md": webhooks_content,
        "database_integration.md": db_integration_content,
        "billing_disputes.txt": billing_disputes_content,
        "refund_policy.txt": refund_policy_content,
        "duplicate_charges.md": duplicate_charges_content,
        "payment_failures.txt": payment_failures_content,
        "browser_cache_issues.md": browser_cache_content,
        "cookie_clearing.txt": cookie_clearing_content,
        "user_permissions.md": user_permissions_content
    }
    
    for filename, content in files.items():
        with open(data_dir / filename, "w", encoding="utf-8") as f:
            f.write(content)
            
    print("Successfully generated all text and markdown knowledge base documents.")

    # Try to compile PDF using reportlab if available
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
        
        pdf_path = data_dir / "password_reset_guide.pdf"
        
        c = canvas.Canvas(str(pdf_path), pagesize=letter)
        width, height = letter
        
        # Title
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, password_reset_title)
        
        # Draw horizontal rule
        c.setLineWidth(1)
        c.line(50, height - 60, width - 50, height - 60)
        
        # Paragraphs
        c.setFont("Helvetica", 10)
        y = height - 85
        
        for para in password_reset_paras:
            # Word wrapping for Reportlab Canvas
            words = para.split(' ')
            line = ""
            for word in words:
                # Check line width
                if c.stringWidth(line + " " + word, "Helvetica", 10) < (width - 100):
                    line = line + " " + word if line else word
                else:
                    c.drawString(50, y, line)
                    y -= 14
                    line = word
                    if y < 50:
                        c.showPage()
                        c.setFont("Helvetica", 10)
                        y = height - 50
            if line:
                c.drawString(50, y, line)
                y -= 22
                if y < 50:
                    c.showPage()
                    c.setFont("Helvetica", 10)
                    y = height - 50
                    
        c.save()
        print(f"Successfully compiled PDF document: {pdf_path}")
        
    except ImportError:
        print("ReportLab is not installed yet. Skipping PDF generation (will be compiled after requirements are installed).")

if __name__ == "__main__":
    generate_all()
